# Generated by Django 2.2.6 on 2019-10-13 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191013_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 14, 17, 3, 693946, tzinfo=utc)),
        ),
    ]
