# Generated by Django 2.2.6 on 2019-10-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191013_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
