# Generated by Django 2.2.7 on 2019-11-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
