# Generated by Django 2.2.7 on 2019-11-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entry.Host')),
            ],
        ),
    ]
