# Generated by Django 2.2.7 on 2019-11-22 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0004_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='visitor',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
