# Generated by Django 2.2.7 on 2019-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0005_auto_20191122_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
