# Generated by Django 2.2.7 on 2019-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0007_auto_20191122_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
